config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/destroy'

  get 'sessions/create'

  delete '/pins' => 'pins#delete_all'

  get 'static_pages/home', as: :home

  get 'static_pages/about', as: :about

  root to: 'static_pages#home'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations', :sessions => 'users/sessions'}

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :pins

  resources :boards

  resources :users

end

app/models/board.rb
class Board < ActiveRecord::Base
	belongs_to :user
	has_many :pins 

	validates :name, :user_id, presence: true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.paginate(:page => params[:page], :per_page => 8)
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to '/pins/new/', notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :about, :user_id)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :full_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<div class="container">
<h1>board to be wild.</h1>
<%= will_paginate @boards %>

<div id="columns">
    <% @boards.each do |board| %>
      <div class="item-background">
        <div class="item-info">
          <h3><%= board.name rescue "N/A" %></h3>
          <h4><%= board.about rescue "N/A" %></h4>
          <h4><%= board.user.full_name rescue "N/A" %></h4>
        </div>
        <div class="item-links">
          <%= link_to 'Show', board %>
          <%= link_to 'Edit', edit_board_path(board) %>
          <%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
        </div>
    <% end %>
</div>

<br>

<%= link_to 'New Board', new_board_path %>

<br>

</div>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @board.name rescue "N/A" %>
</p>

<p>
  <strong>About:</strong>
  <%= @board.about rescue "N/A" %>
</p>

<p>
  <strong>User:</strong>
  <%= @board.user.first_name rescue "N/A" %>
</p>

<p>Pins on this Board:</p>
	<ul>
		<% @board.pins.each do |pin| %>
		<li><%= link_to pin.name, pin_path(pin) %></li>
		<% end %>
	</ul>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>